#+title: What is this website for anyway?
#+date: 2026-09-11
#+description: My motivations and plans going forward.
#+filetags: :meta:
#+options: toc:nil num:nil

* Background and influences

Ever since I became interested in programming in 2017, I have consumed content
about it online. When I was a little younger, the vast majority of this content
came from YouTube. In the beginning, it was really just hot topics from Twitter
or Hacker News digested *for me*. Before AI, this was the general content model
of most popular tech and software YouTubers, such as
[[https://www.youtube.com/c/theprimeagen][ThePrimeagen]].

However, as I started getting closer to the source, I found that the majority
of the cool shit online came from nerds just writing or recording their
thoughts. And generally, that's exactly what I am trying to do here: stop being
a constant consumer, level up, focus on growing and learning, and talk about
that process in the open.

I've spent /too much/ time letting all my thoughts spin around in my brain, so
this place will force me to formalize them and stop ruminating. Furthermore, I
have spent *way too much* time fiddling around with blog and static website
generation techniques and technologies, so it's time to stop dawdling and
start creating.

This wave of motivation is no coincidence. I recently graduated with a CS
degree, and I need a job. But really, I just need to showcase to the world—and
perhaps myself—that I am not a bot. The ideas and opinions on this website come
from my brain: artisanally crafted content!

* Recent work

The homepage lists the projects I am working on. Over the summer, I spent most
of my time working on
[[https://github.com/vetr0s/mach][Mach/mach.h]] and applying to jobs, which has been simultaneously the best and
worst time ever. Making games was my original motivation for learning to code,
and my appreciation for the problem space has only grown! That being said,
*owning the entire stack* is cumbersome, to say the least. As life has gotten
busier, I have found it hard to rationalize picking the project back up again.

* Moving forward

Most of my project-based work has come to a halt in the last month because I
have actually gotten some interviews (thank God). So retrospectives will be
delayed for a while. The upcoming writing I want to do will focus more on the
life and philosophy concepts I have been thinking about during my post-undergrad
job search.

* Closing thoughts

Thank you for taking the time to read my first ramblings published here!

Overall, my goal is not to come off as an amazing computer scientist, engineer,
or thinker. I am simply a 21-year-old dude trying to start a career in software.
If you get anything out of my website, then I have achieved more than I set out
to do.

Honestly, there is a noticeable impact on my quality of life when I am
regularly reading, writing down my thoughts, and managing my time. This website
just happens to aid in that process while also serving as my portfolio.

/Live long and prosper/
